# Generated by Django 4.1.7 on 2026-02-24 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0002_alter_interviewanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='interviews/')),
                ('transcript', models.TextField()),
                ('confidence_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='interviewvideo',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterviewAnswer',
        ),
        migrations.DeleteModel(
            name='InterviewVideo',
        ),
    ]
