# Generated by Django 4.1.7 on 2026-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewresult_remove_interviewvideo_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='video',
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='question',
            field=models.TextField(default='No Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
