# Generated by Django 4.1.7 on 2026-03-26 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0004_remove_interviewresult_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='emotion',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='grade',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
