# Generated by Django 4.1.7 on 2026-03-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviewresult_emotion_interviewresult_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='clarity',
            field=models.IntegerField(default=0),
        ),
    ]
