# Generated by Django 4.1.7 on 2026-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_interviewresult_clarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='clarity',
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='round',
            field=models.CharField(default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='accuracy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='communication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='confidence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='emotion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
