# Generated by Django 4.1.7 on 2026-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_remove_interviewresult_clarity_interviewresult_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='round',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('HR', 'HR'), ('TECH', 'Technical')], default='BASIC', max_length=10),
        ),
    ]
