# Generated by Django 4.1.7 on 2026-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_answer_remove_question_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default='Your answer here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
