# Generated by Django 4.1.7 on 2026-03-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
