# Generated by Django 4.1.7 on 2026-03-17 07:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_resume_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.CharField(choices=[('software', 'Software'), ('banking', 'Banking'), ('finance', 'Finance'), ('medical', 'Medical'), ('teaching', 'Teaching'), ('marketing', 'Marketing'), ('hr', 'HR')], default='software', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='software', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/', validators=[accounts.models.validate_file_size]),
        ),
    ]
